/**
 * Generates supabase/seed/seed.sql: 25 fully-mapped demo courses with
 * realistic geometry (tees, F/C/B green points, pars, stroke indexes, ratings),
 * the 27-drill practice library, and the badge set.
 * Deterministic (seeded PRNG) so the seed is reproducible.
 * Run: node supabase/seed/generate-seed.ts > supabase/seed/seed.sql
 */

const CITIES: [string, string, string, number, number][] = [
  ["Pebble Creek National", "Monterey", "CA", 36.567, -121.95],
  ["Whispering Pines GC", "Pinehurst", "NC", 35.19, -79.47],
  ["Eagle Ridge Links", "Galena", "IL", 42.42, -90.43],
  ["Bluewater Dunes", "Kiawah Island", "SC", 32.61, -80.05],
  ["High Desert Canyon", "Scottsdale", "AZ", 33.68, -111.87],
  ["Maple Hollow CC", "Grand Rapids", "MI", 42.96, -85.67],
  ["Cypress Bend", "Naples", "FL", 26.14, -81.79],
  ["Timber Gate GC", "Bend", "OR", 44.06, -121.31],
  ["Prairie Sky Golf Club", "Lincoln", "NE", 40.81, -96.68],
  ["Stonebridge Meadows", "Fayetteville", "AR", 36.03, -94.11],
  ["Harbor Point Links", "Traverse City", "MI", 44.76, -85.62],
  ["Red Rock Mesa", "St. George", "UT", 37.09, -113.58],
  ["Willow Bend National", "Plano", "TX", 33.05, -96.75],
  ["Foxfire Glen", "Asheville", "NC", 35.59, -82.55],
  ["Lakeshore Commons", "Madison", "WI", 43.07, -89.4],
  ["Granite Falls GC", "Concord", "NH", 43.21, -71.54],
  ["Sunset Valley", "Boulder", "CO", 40.01, -105.27],
  ["Osprey Cove", "Savannah", "GA", 32.08, -81.1],
  ["Bear Hollow", "Park City", "UT", 40.65, -111.5],
  ["Ninteen Eagles GC", "Columbus", "OH", 39.96, -83.0],
  ["Saltgrass Point", "Corpus Christi", "TX", 27.8, -97.4],
  ["Copper Creek Ranch", "Boise", "ID", 43.62, -116.21],
  ["Heron Marsh", "Charleston", "SC", 32.78, -79.93],
  ["Aspen Run", "Flagstaff", "AZ", 35.2, -111.65],
  ["Old Mill Course", "Lancaster", "PA", 40.04, -76.3],
];

// Deterministic PRNG (mulberry32)
function rng(seed: number) {
  return () => {
    seed |= 0; seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const PAR_SETS = [
  [4,5,3,4,4,3,5,4,4, 4,3,5,4,4,3,4,5,4], // 72
  [4,4,3,5,4,3,4,5,4, 3,4,4,5,4,4,3,4,5], // 72
  [5,4,3,4,4,4,3,5,4, 4,4,3,4,5,4,3,4,4], // 70? compute anyway
];

function destination(lat: number, lng: number, bearingDeg: number, meters: number): [number, number] {
  const R = 6371008.8, br = (bearingDeg * Math.PI) / 180;
  const φ1 = (lat * Math.PI) / 180, λ1 = (lng * Math.PI) / 180, δ = meters / R;
  const φ2 = Math.asin(Math.sin(φ1) * Math.cos(δ) + Math.cos(φ1) * Math.sin(δ) * Math.cos(br));
  const λ2 = λ1 + Math.atan2(Math.sin(br) * Math.sin(δ) * Math.cos(φ1), Math.cos(δ) - Math.sin(φ1) * Math.sin(φ2));
  return [(φ2 * 180) / Math.PI, (λ2 * 180) / Math.PI];
}

const q = (s: string) => s.replace(/'/g, "''");
const pt = (lat: number, lng: number) => `st_geogfromtext('POINT(${lng.toFixed(6)} ${lat.toFixed(6)})')`;

let out = "-- Generated by generate-seed.ts — do not edit by hand.\nbegin;\n";

for (let ci = 0; ci < CITIES.length; ci++) {
  const [name, city, region, clat, clng] = CITIES[ci];
  const rand = rng(ci + 1);
  const pars = PAR_SETS[ci % PAR_SETS.length];
  const par = pars.reduce((a, b) => a + b, 0);
  const cid = `'c0000000-0000-4000-8000-${String(ci + 1).padStart(12, "0")}'::uuid`;
  out += `insert into courses (id, name, city, region, country, location, source) values (${cid}, '${q(name)}', '${q(city)}', '${region}', 'USA', ${pt(clat, clng)}, 'seed');\n`;

  const slope = 118 + Math.round(rand() * 22);           // 118–140
  const cr = par - 1.5 + rand() * 4;                     // near par
  for (const [tee, factor] of [["Blue", 1.0], ["White", 0.93], ["Gold", 0.85]] as const) {
    out += `insert into course_tees (course_id, name, course_rating, slope_rating, course_rating_9_front, course_rating_9_back, total_yards) values (${cid}, '${tee}', ${(cr * factor + (1 - factor) * par * 0.98).toFixed(1)}, ${Math.max(110, Math.round(slope * factor))}, ${((cr * factor) / 2).toFixed(1)}, ${((cr * factor) / 2 + 0.2).toFixed(1)}, ${Math.round(6900 * factor)});\n`;
  }

  // Shuffle stroke indexes deterministically (odd front, even back convention).
  const si = Array.from({ length: 18 }, (_, i) => i + 1).sort(() => rand() - 0.5);

  let bearing = rand() * 360;
  let [lat, lng] = destination(clat, clng, rand() * 360, 200);
  for (let h = 0; h < 18; h++) {
    const p = pars[h];
    const yards = p === 3 ? 140 + rand() * 80 : p === 4 ? 330 + rand() * 120 : 480 + rand() * 90;
    const meters = yards * 0.9144;
    bearing = (bearing + 60 + rand() * 100) % 360;       // routing wanders like a real course
    const [gLat, gLng] = destination(lat, lng, bearing, meters);
    const [fLat, fLng] = destination(gLat, gLng, (bearing + 180) % 360, 12);
    const [bLat, bLng] = destination(gLat, gLng, bearing, 12);
    const teeYards = { Blue: Math.round(yards), White: Math.round(yards * 0.93), Gold: Math.round(yards * 0.85) };
    out += `insert into course_holes (course_id, hole_number, par, stroke_index, yards_by_tee, tee_points, green_front, green_center, green_back) values (` +
      `${cid}, ${h + 1}, ${p}, ${si[h]}, '${JSON.stringify(teeYards)}', ` +
      `'${JSON.stringify({ Blue: { lat: +lat.toFixed(6), lng: +lng.toFixed(6) } })}', ` +
      `${pt(fLat, fLng)}, ${pt(gLat, gLng)}, ${pt(bLat, bLng)});\n`;
    // next tee sits ~40m past this green
    [lat, lng] = destination(gLat, gLng, bearing, 40);
  }
}

// ---- Practice drills from the engine library ----
import { DRILLS } from "../../packages/engine/src/drills.ts";
for (const d of DRILLS) {
  out += `insert into practice_drills (slug, title, category, description, rubric, est_minutes) values ('${d.slug}', '${q(d.title)}', '${d.category}', '${q(d.description)}', '${q(JSON.stringify({ scoring: d.scoring, reps: d.reps, targets: d.targets }))}', ${d.estMinutes});\n`;
}

// ---- Badges: cosmetic only (Fix #14) ----
const BADGES: [string, string, string, string][] = [
  ["first-round", "Opening Round", "Complete your first round", "flag"],
  ["birdie", "Birdie Maker", "Card your first birdie", "bird"],
  ["eagle", "Eagle Eye", "Card an eagle", "eagle"],
  ["streak-3", "Weekend Regular", "Play 3 weeks in a row", "calendar"],
  ["no-three-putt", "Silky Touch", "18 holes without a 3-putt", "putter"],
  ["all-fairways", "Sniper", "Hit every fairway in a round", "target"],
  ["up-down-5", "Scrambler", "5 up-and-downs in one round", "wedge"],
  ["practice-10", "Range Rat", "Complete 10 practice sessions", "bucket"],
  ["mapped-course", "Cartographer", "Map a course for the community", "map"],
  ["sub-80", "Breaking 80", "Shoot in the 70s", "trophy"],
];
for (const [slug, title, desc, icon] of BADGES) {
  out += `insert into badges (slug, title, description, icon) values ('${slug}', '${q(title)}', '${q(desc)}', '${icon}');\n`;
}
out += "commit;\n";
console.log(out);
